version: "3.8"

services:
    db:
        image: postgres:13-alpine
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
            POSTGRES_USER: guacatea
            POSTGRES_PASSWORD: guacatea
            POSTGRES_DB: guacatea
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data

    app:
        build: .
        command: python run.py run-app
        ports:
            - "${FLASK_RUN_PORT:-5000}:${FLASK_RUN_PORT:-5000}"
        volumes:
            - ./guacatea_market:/opt/app
        depends_on:
            - db
            - adminer
        environment:
            FLASK_ENV: development
            FLASK_DEBUG: 1
            # FLASK_APP: market/__init__.py
    
    start_app:
        build: .
        command: python run.py migrate-db
        restart: on-failure
        depends_on:
            - db
            - adminer

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    postgres-db-volume:
