version: "3.8"

services:
    app:
        build: .
        command: flask run --host=0.0.0.0
        ports:
            - "${FLASK_RUN_PORT:-5000}:${FLASK_RUN_PORT:-5000}"
        volumes:
            - ./guacatea_market:/opt/app
        depends_on:
            - db
            - adminer
        environment:
            FLASK_ENV: development
            FLASK_DEBUG: 1
            FLASK_APP: market/__init__.py

    db:
        image: postgres:13-alpine
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: guacatea
            POSTGRES_PASSWORD: guacatea
            POSTGRES_DB: guacatea
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    postgres-db-volume: