version: "3.8"

services:
    app:
        build: .
        command: python run.py
        ports:
            - "${FLASK_RUN_PORT:-5000}:${FLASK_RUN_PORT:-5000}"
        volumes:
            - ./guacatea_market:/opt/app
        depends_on:
            - db
            - adminer
        environment:
            FLASK_ENV: development

    db:
        image: postgres:13-alpine
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: guacatea
            POSTGRES_PASSWORD: guacatea
            POSTGRES_DB: guacatea

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
